/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aulasql;
import static aulasql.Conexao.con;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anchieta
 */
public class vendas extends javax.swing.JFrame {
    
       DefaultTableModel model;

    /**
     * Creates new form telavendas
     */
    public vendas() {
        initComponents();
     Conexao.Conectar(); //chama o metodo Conectar de dentro da classe conexao
        TABELAVENDAS.getColumnModel().getColumn(0).setMaxWidth(50); // altera a largura da coluna 0
        TABELAVENDAS.getColumnModel().getColumn(1).setMaxWidth(420); // altera a largura da coluna 1
        TABELAVENDAS.getColumnModel().getColumn(2).setMaxWidth(420); // altera a largura da coluna 2
        TABELAVENDAS.getColumnModel().getColumn(3).setMaxWidth(100); // altera a largura da coluna 3
        TABELAVENDAS.getColumnModel().getColumn(4).setMaxWidth(100); // altera a largura da coluna 4
        TABELAVENDAS.getColumnModel().getColumn(5).setMaxWidth(420); // altera a largura da coluna 5
        model =  (DefaultTableModel) TABELAVENDAS.getModel(); //instancia model para pegar as caracteristicas do jTable1
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNomeVnd = new javax.swing.JTextField();
        tfPreco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfTipo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        tfNumeroVnd = new javax.swing.JTextField();
        btnInlcuirProd = new javax.swing.JButton();
        btnSalvarVnd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfCodigoVnd = new javax.swing.JTextField();
        btnAlterarProd = new javax.swing.JButton();
        btnIncluirVnd = new javax.swing.JButton();
        btnSalvarProd = new javax.swing.JButton();
        btnConsultarVnd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABELAVENDAS = new javax.swing.JTable();
        btnAlterarVnd = new javax.swing.JButton();
        tfCodProduto = new javax.swing.JTextField();
        btnConsultarProd = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("LIMPAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("TELEFONE:");

        jLabel1.setText("NOME:");

        jLabel2.setText("TIPO DE PRODUTO:");

        jLabel6.setText("CÓDIGO DA VENDA:");

        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnInlcuirProd.setText("INCLUIR");
        btnInlcuirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInlcuirProdActionPerformed(evt);
            }
        });

        btnSalvarVnd.setText("SALVAR");
        btnSalvarVnd.setEnabled(false);
        btnSalvarVnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarVndActionPerformed(evt);
            }
        });

        jLabel7.setText("CÓDIGO DO PRODUTO:");

        btnAlterarProd.setText("ALTERAR");
        btnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdActionPerformed(evt);
            }
        });

        btnIncluirVnd.setText("INCLUIR");
        btnIncluirVnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirVndActionPerformed(evt);
            }
        });

        btnSalvarProd.setText("SALVAR");
        btnSalvarProd.setEnabled(false);
        btnSalvarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProdActionPerformed(evt);
            }
        });

        btnConsultarVnd.setText("CONSULTAR");
        btnConsultarVnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVndActionPerformed(evt);
            }
        });

        jLabel4.setText("PREÇO:");

        TABELAVENDAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Telefone", "CódigoP", "Descrição", "Valor"
            }
        ));
        jScrollPane1.setViewportView(TABELAVENDAS);

        btnAlterarVnd.setText("ALTERAR");
        btnAlterarVnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarVndActionPerformed(evt);
            }
        });

        btnConsultarProd.setText("CONSULTAR");
        btnConsultarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProdActionPerformed(evt);
            }
        });

        jButton4.setText("DELETAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultarVnd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlterarVnd, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIncluirVnd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(btnSalvarVnd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfCodigoVnd)
                    .addComponent(tfNomeVnd)
                    .addComponent(tfNumeroVnd))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(165, 165, 165)
                                    .addComponent(btnAlterarProd))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnConsultarProd)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnInlcuirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(btnSalvarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 446, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tfCodigoVnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(tfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNomeVnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNumeroVnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIncluirVnd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalvarVnd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterarVnd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultarVnd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInlcuirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalvarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarVndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVndActionPerformed
        // TODO add your handling code here:
        //Conexao.Conectar();

        String sql;
        //model.setRowCount(0); //limpa a tabela toda vez que clicar no botao consultar
        try{
            sql = "select * from cliente where idCliente = '" + tfCodigoVnd.getText() + "' order by idCliente desc"; //cria a instrução de pesquisa
            //a partir do nome digitado no campo tfNome

            Statement stm = con.createStatement(); //cria uma declaracao stm para a variavel con de conexao

            ResultSet rs = stm.executeQuery(sql); // cria uma variavel rs como resultset (resultado) da execucao da consulta sql
            rs.first();  //move o ponteiro do BD para o primeiro registro

            String[] linha= new String[]{rs.getString("idCliente"),rs.getString("nome"),
                rs.getString("numero")}; // cria um vetor chmado linha que contem o resultado da pesquisa com todos os campos

            model.addRow(linha); // adiciona uma linha na instancia model criada, colocando o conteudo do vetor linha,
            //ou seja, cada um dos itens do vetor correspondem a uma das colunas da tabela

            //tfCodigo.setText(rs.getString("codigo")); //coloca o conteudo do campo codigo no tdCodigo
            //tfEndereco.setText(rs.getString("endereco"));
            //tfTelefone.setText(rs.getString("telefone"));
            //tfCelular.setText(rs.getString("celular"));
            //tfEmail.setText(rs.getString("email"));

            while(rs.next()){
                linha= new String[]{rs.getString("idCliente"),rs.getString("nome"),
                    rs.getString("numero")};
                //cada vez que passar pelo while cria uma variavel linha contendo o conteudo dos campos do BD
                //e joga dentro do vetor chamado linha
                model.addRow(linha); // adiciona uma linha na instancia model com o conteudo do vetor

            }

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Erro ao consultar, tente novamente"
                ,"ERRO",JOptionPane.INFORMATION_MESSAGE);
            //mostra caixa de mensagem de erro com icone de informacao
        }
    }//GEN-LAST:event_btnConsultarVndActionPerformed

    private void btnSalvarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProdActionPerformed
        // TODO add your handling code here:
        String sql;
        String codigo, dcc, vlr;
        codigo = tfCodProduto.getText();
        dcc = tfNomeVnd.getText();
        vlr = tfNumeroVnd.getText();
        try{
            sql="update cliente set produtos= " + codigo + ", descricao='" + dcc + "', preco='" + vlr + "' where idProduto = " +codigo;

            Statement stm = con.prepareStatement(sql);
            stm.execute(sql);
            tfCodProduto.setText("");
            tfTipo.setText("");
            tfPreco.setText("");
            tfNomeVnd.requestFocus();
            btnSalvarVnd.setEnabled(false);
            model.setRowCount(0);
        }
        catch(SQLException e){

            JOptionPane.showMessageDialog(null, "Erro ao alterar, tente novamente" + e,"ERRO",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnSalvarProdActionPerformed

    private void btnIncluirVndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirVndActionPerformed
        // TODO add your handling code here:

        String sql;
        String codigo, Nome, Telefone;
        codigo = tfCodigoVnd.getText();
        Nome = tfNomeVnd.getText();
        Telefone = tfNumeroVnd.getText();
        try{
            sql="insert into cliente (idCliente, nome, numero"
            + " nome) values ("  + codigo + ",'" + Nome + "','" + Telefone + "')";

            Statement stm = con.prepareStatement(sql);
            stm.execute(sql);
            tfCodigoVnd.setText("");
            tfNomeVnd.setText("");
            tfNumeroVnd.setText("");
            tfCodigoVnd.requestFocus();

        }
        catch(SQLException e){

            JOptionPane.showMessageDialog(null, "Erro ao incluir, tente novamente" + e,"ERRO",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnIncluirVndActionPerformed

    private void btnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdActionPerformed
        // TODO add your handling code here:
        int linha = TABELAVENDAS.getSelectedRow();

        tfCodigoVnd.setText((String) TABELAVENDAS.getValueAt(linha, 0)); //coloca o conteudo do campo codigo no tdCodigo
        tfNomeVnd.setText((String) TABELAVENDAS.getValueAt(linha, 1));
        tfNumeroVnd.setText((String) TABELAVENDAS.getValueAt(linha, 2));
        tfCodProduto.setText((String) TABELAVENDAS.getValueAt(linha, 3));
        tfTipo.setText((String) TABELAVENDAS.getValueAt(linha, 4));
        tfPreco.setText((String) TABELAVENDAS.getValueAt(linha, 5));
        tfNomeVnd.requestFocus();
        btnSalvarVnd.setEnabled(true);
    }//GEN-LAST:event_btnAlterarProdActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int opcao = JOptionPane.showConfirmDialog(null, "Confirma exclusão", "Excluindo...", JOptionPane.YES_NO_OPTION);

        int linha = TABELAVENDAS.getSelectedRow();
        String sql;
        String codigo;
        codigo = (String) TABELAVENDAS.getValueAt(linha, 0);

        if (opcao==0){
            try{
                sql="delete from cliente where codigo = " + codigo;

                Statement stm = con.prepareStatement(sql);
                stm.execute(sql);
            }
            catch(SQLException e){

                JOptionPane.showMessageDialog(null, "Erro ao excluir, tente novamente" + e,"ERRO",JOptionPane.INFORMATION_MESSAGE);

            }
        }
        model.setRowCount(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tfCodigoVnd.setText("");
        tfNomeVnd.setText("");
        tfNumeroVnd.setText("");
        tfCodProduto.setText("");
        tfTipo.setText("");
        tfPreco.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnConsultarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProdActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        //Conexao.Conectar();

        String sql;
        //model.setRowCount(0); //limpa a tabela toda vez que clicar no botao consultar
        try{
            sql = "select * from produtos where idProduto = '" + tfCodProduto.getText() + "' order by idVendas descricao"; //cria a instrução de pesquisa
            //a partir do nome digitado no campo tfNome

            Statement stm = con.createStatement(); //cria uma declaracao stm para a variavel con de conexao

            ResultSet rs = stm.executeQuery(sql); // cria uma variavel rs como resultset (resultado) da execucao da consulta sql
            rs.first();  //move o ponteiro do BD para o primeiro registro

            String[] linha= new String[]{rs.getString("idProduto"),rs.getString("descricao"),
                rs.getString("preco")}; // cria um vetor chmado linha que contem o resultado da pesquisa com todos os campos

            model.addRow(linha); // adiciona uma linha na instancia model criada, colocando o conteudo do vetor linha,
            //ou seja, cada um dos itens do vetor correspondem a uma das colunas da tabela

            //tfCodigo.setText(rs.getString("codigo")); //coloca o conteudo do campo codigo no tdCodigo
            //tfEndereco.setText(rs.getString("endereco"));
            //tfTelefone.setText(rs.getString("telefone"));
            //tfCelular.setText(rs.getString("celular"));
            //tfEmail.setText(rs.getString("email"));

            while(rs.next()){
                linha= new String[]{rs.getString("idProduto"),rs.getString("descricao"),
                    rs.getString("preco")};
                //cada vez que passar pelo while cria uma variavel linha contendo o conteudo dos campos do BD
                //e joga dentro do vetor chamado linha
                model.addRow(linha); // adiciona uma linha na instancia model com o conteudo do vetor

            }

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Erro ao consultar, tente novamente"
                ,"ERRO",JOptionPane.INFORMATION_MESSAGE);
            //mostra caixa de mensagem de erro com icone de informacao
        }
    }//GEN-LAST:event_btnConsultarProdActionPerformed

    private void btnSalvarVndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarVndActionPerformed
        // TODO add your handling code here:
        String sql;
        String codigo, nome, telefone;
        codigo = tfCodigoVnd.getText();
        nome = tfNomeVnd.getText();
        telefone = tfNumeroVnd.getText();

        try{
            sql="update cliente set idCliente= " + codigo + ", nome='" + nome + "', numero='" + telefone + "' where idCliente = " +codigo;

            Statement stm = con.prepareStatement(sql);
            stm.execute(sql);
            tfCodigoVnd.setText("");
            tfNomeVnd.setText("");
            tfNumeroVnd.setText("");
            tfNomeVnd.requestFocus();
            btnSalvarVnd.setEnabled(false);
            model.setRowCount(0);
        }
        catch(SQLException e){

            JOptionPane.showMessageDialog(null, "Erro ao alterar, tente novamente" + e,"ERRO",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnSalvarVndActionPerformed

    private void btnAlterarVndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarVndActionPerformed
        // TODO add your handling code here:
        int linha = TABELAVENDAS.getSelectedRow();

        tfCodigoVnd.setText((String) TABELAVENDAS.getValueAt(linha, 0)); //coloca o conteudo do campo codigo no tdCodigo
        tfNomeVnd.setText((String) TABELAVENDAS.getValueAt(linha, 1));
        tfNumeroVnd.setText((String) TABELAVENDAS.getValueAt(linha, 2));
        tfCodProduto.setText((String) TABELAVENDAS.getValueAt(linha, 3));
        tfTipo.setText((String) TABELAVENDAS.getValueAt(linha, 4));
        tfPreco.setText((String) TABELAVENDAS.getValueAt(linha, 5));
        tfNomeVnd.requestFocus();
        btnSalvarVnd.setEnabled(true);
    }//GEN-LAST:event_btnAlterarVndActionPerformed

    private void btnInlcuirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInlcuirProdActionPerformed
        // TODO add your handling code here:
        String sql;
        String cdgp, dcc, vlr;
        cdgp = tfCodProduto.getText();
        dcc = tfTipo.getText();
        vlr = tfPreco.getText();
        try{
            sql="insert into produtos (idProduto, descricao, preco"
            + " descricao) values ("  + cdgp + ",'" + dcc + "','" + vlr + "')";

            Statement stm = con.prepareStatement(sql);
            stm.execute(sql);
            tfCodProduto.setText("");
            tfTipo.setText("");
            tfPreco.setText("");
            tfCodigoVnd.requestFocus();

        }
        catch(SQLException e){

            JOptionPane.showMessageDialog(null, "Erro ao incluir, tente novamente" + e,"ERRO",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnInlcuirProdActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        try{
            Conexao.con.close();
        }
        catch (SQLException e){
            System.out.println(e);
        }
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABELAVENDAS;
    private javax.swing.JButton btnAlterarProd;
    private javax.swing.JButton btnAlterarVnd;
    private javax.swing.JButton btnConsultarProd;
    private javax.swing.JButton btnConsultarVnd;
    private javax.swing.JButton btnIncluirVnd;
    private javax.swing.JButton btnInlcuirProd;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvarProd;
    private javax.swing.JButton btnSalvarVnd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfCodProduto;
    private javax.swing.JTextField tfCodigoVnd;
    private javax.swing.JTextField tfNomeVnd;
    private javax.swing.JTextField tfNumeroVnd;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfTipo;
    // End of variables declaration//GEN-END:variables
}
