/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aulasql;

import static aulasql.Conexao.con;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Anchieta
 */
public class produtos extends javax.swing.JFrame {

    /**
     * Creates new form produtos
     */
    public produtos() {
        initComponents();
        Conexao.Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfCodigoProd = new javax.swing.JTextField();
        btIncluirEmp = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnLimparEmp = new javax.swing.JButton();
        tfTipoProduto = new javax.swing.JTextField();
        btnConsultarEmp = new javax.swing.JButton();
        btnSairEmp = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnExcluirEmp = new javax.swing.JButton();
        btnAlterarEmp = new javax.swing.JButton();
        fPreco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfLote = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("CÓDIGO DO PRODUTO:");

        jLabel13.setText("PREÇO:");

        tfCodigoProd.setBackground(new java.awt.Color(255, 255, 153));

        btIncluirEmp.setText("INCLUIR");
        btIncluirEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirEmpActionPerformed(evt);
            }
        });

        jLabel9.setText("TIPO DE PRODUTO:");

        btnLimparEmp.setText("LIMPAR");
        btnLimparEmp.setToolTipText("");
        btnLimparEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparEmpActionPerformed(evt);
            }
        });

        btnConsultarEmp.setText("CONSULTAR");
        btnConsultarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEmpActionPerformed(evt);
            }
        });

        btnSairEmp.setText("SAIR");
        btnSairEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairEmpActionPerformed(evt);
            }
        });

        jLabel10.setText("FORNECEDOR:");

        btnExcluirEmp.setText("EXCLUIR");
        btnExcluirEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEmpActionPerformed(evt);
            }
        });

        btnAlterarEmp.setText("ALTERAR");
        btnAlterarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarEmpActionPerformed(evt);
            }
        });

        jLabel14.setText("LOTE:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Teste", " ", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btIncluirEmp)
                                .addGap(64, 64, 64)
                                .addComponent(btnConsultarEmp)
                                .addGap(65, 65, 65)
                                .addComponent(btnAlterarEmp))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnLimparEmp)
                                .addGap(94, 94, 94)
                                .addComponent(btnSairEmp)
                                .addGap(62, 62, 62)
                                .addComponent(btnExcluirEmp))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addComponent(jLabel8))
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfTipoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                                .addComponent(tfCodigoProd)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(142, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(fPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(120, 120, 120)
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfLote, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tfCodigoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(tfLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(fPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIncluirEmp)
                    .addComponent(btnConsultarEmp)
                    .addComponent(btnAlterarEmp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparEmp)
                    .addComponent(btnSairEmp)
                    .addComponent(btnExcluirEmp))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirEmpActionPerformed

        // TODO add your handling code here:

        String sql;
        String Nome, Lote, Preco;

        Nome = tfTipoProduto.getText();
        Lote = tfLote.getText();
  
        Preco = fPreco.getText();


        try{
            sql="insert into produtos (nome, lote, idForncedor, preco, email)"
            + " values ('" + Nome + "','" + Lote + "','" + Preco +"')";

            System.out.println(sql);

            Statement stm = con.prepareStatement(sql);
            stm.execute(sql);

            JOptionPane.showMessageDialog(null, "Sucesso ao incluir os dados",
                    "Inclusão",JOptionPane.INFORMATION_MESSAGE);
            tfCodigoProd.requestFocus();

        }
        catch(SQLException e){

            JOptionPane.showMessageDialog(null, "OPAAA, houve um erro ao incluir"
+ " os dados no banco, tente novamente" + e,"ERRO",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btIncluirEmpActionPerformed

    private void btnLimparEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparEmpActionPerformed
        // TODO add your handling code here:
        tfCodigoProd.setText("");
        tfTipoProduto.setText("");
        tfLote.setText("");

        fPreco.setText("");
       
    }//GEN-LAST:event_btnLimparEmpActionPerformed

    private void btnConsultarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEmpActionPerformed
        // TODO add your handling code here:]

        String sql;
        String idProduto;
        idProduto = tfCodigoProd.getText();
        try{
            sql = "select * from produto where idProduto = " + idProduto;

            Statement stm = con.createStatement();

            ResultSet rs = stm.executeQuery(sql);
            rs.first();

            tfCodigoProd.setText(rs.getString("idProduto"));
            tfTipoProduto.setText(rs.getString("nome"));
            tfLote.setText(rs.getString("lote"));
          
            fPreco.setText(rs.getString("preco"));
            
        }    
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Coloque outro código do "
       + "fornecedor e tente novamente","ERRO",JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_btnConsultarEmpActionPerformed

    private void btnSairEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairEmpActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btnSairEmpActionPerformed

    private void btnExcluirEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEmpActionPerformed
        // TODO add your handling code here:

        String sql;
        String IdProduto;
        int opc;
        IdProduto = tfCodigoProd.getText();

        try{
            opc = JOptionPane.showConfirmDialog(null, "Confirma exclusão", 
                 "Excluindo...", 0);
            if (opc == 0){
                sql="DELETE FROM produto where idProduto ="+ IdProduto;

                Statement stm = con.prepareStatement(sql);
                stm.execute(sql);

                tfCodigoProd.setText("");
                tfTipoProduto.setText("");
                tfLote.setText("");                
                fPreco.setText("");
                

                JOptionPane.showMessageDialog(null, "Sucesso ao excluir os "
                   + "dados","Inclusão",JOptionPane.INFORMATION_MESSAGE);

                tfCodigoProd.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "cancelamento na operação!"
               ,"Cancelado",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "coloque o codigo do cliente e"
              + " tente novamente" + e,"ERRO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirEmpActionPerformed

    private void btnAlterarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarEmpActionPerformed
        // TODO add your handling code here:

        String sql;
        String idProduto;
        String Nome, Lote, Preco, idFornecedor;

        idProduto = tfCodigoProd.getText();
        Nome = tfTipoProduto.getText();
        Lote = tfLote.getText();
        Preco = fPreco.getText();
        

        try{

            sql="update produto set nome = '" + Nome + "',"
            + "lote = '" + Lote + "',"        
            + "preco = '" + Preco + "',"
           
            + "where idProduto = " + idProduto;
            System.out.println(sql);

            Statement stm = con.prepareStatement(sql);
            stm.execute(sql);

            tfCodigoProd.setText("");
            tfTipoProduto.setText("");
            tfLote.setText("");
            
            fPreco.setText("");           

            JOptionPane.showMessageDialog(null, "Houve um sucesso na alteração "
               + "de seus dados","Inclusão",JOptionPane.INFORMATION_MESSAGE);
            tfCodigoProd.requestFocus();

        }
        catch(SQLException e){

          JOptionPane.showMessageDialog(null, "houve um erro ao alterar seus ]"
      + "dados, tente novamente..." + e,"ERRO",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnAlterarEmpActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here
        
        String sql;
        
        try{ 
            
            sql="select nome from funcionario";
            
            Statement stm = con.prepareStatement(sql);
            stm.execute(sql);
        
        }
        
        catch(SQLException e){
            
         JOptionPane.showMessageDialog(null, "Houve um erro ao alterar seus"
     + " dados, tente novamente..." + e,"ERRO",JOptionPane.INFORMATION_MESSAGE);
        
        }
    
   
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIncluirEmp;
    private javax.swing.JButton btnAlterarEmp;
    private javax.swing.JButton btnConsultarEmp;
    private javax.swing.JButton btnExcluirEmp;
    private javax.swing.JButton btnLimparEmp;
    private javax.swing.JButton btnSairEmp;
    private javax.swing.JTextField fPreco;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfCodigoProd;
    private javax.swing.JTextField tfLote;
    private javax.swing.JTextField tfTipoProduto;
    // End of variables declaration//GEN-END:variables
}
